name: Fetch data and create pull request
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  fetchdata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.0.0

      - name: Run fetch data bash script
        run: bash ./scripts/fetchdata.sh

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          title: 'Automated content update'
          branch-suffix: timestamp
          delete-branch: true
          reviewers: isabelle-dr, emmambd
